apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-web-app
spec:
  selector:
    matchLabels:
      app: forum-web-app
  replicas: 2
  template:
    metadata:
      labels:
        app: forum-web-app
    spec:
      containers:
      - name: forum-web-app
        #resources:
          #limits:
           # cpu: 1
           # memory: 1Gi
          #requests:
           # cpu: 100m
          # memory: 250Mi
        image: adilkenzhigaliyev/kenzhigaliyev:test
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080